project/cliente/urls.py
from django.urls import path, include
from . import views

app_name = "cliente"

urlpatterns = [
    path('', views.home, name = "index"),
    path('cliente/', views.cliente_view, name= "cliente"),
    path('accounts/', include('django.contrib.auth.urls')),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("producto/", include("producto.urls")),
]

project/core/urls.py
from django.urls import path, include
from . import views

app_name = "core"

urlpatterns = [
    path('', views.home, name = "index"),
    path("about/", views.about, name="about"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', exit, name= "exit")
]

project/producto/urls.py
from django.urls import path, include
from . import views

app_name = "producto"

urlpatterns = [
    path('', views.home, name = "index"),
    path('accounts/', include('django.contrib.auth.urls')),
]

project/cliente/models.py
from django.db import models

class Pais(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return self.nombre
    
class cliente(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    pais_origen = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    
class juegos(models.Model):
    nombre_juego = models.CharField(max_length=100)
    genero = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.nombre_juego} {self.genero}"



    

project/core/models.py
from django.db import models

# Create your models here.

project/producto/models.py
from django.db import models

# Create your models here.

project/cliente/forms.py
from django import forms


class cliente(forms.Form):
    cliente = forms.CharField()
    apellido = forms.CharField()
    fecha_nacimiento = forms.IntegerField()
    pais_origen = forms.CharField()


class Pais(forms.Form):
    nombre = forms.CharField()

project/cliente/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

def cliente_view(request):
    if request.method == "GET":
        print("+" * 90) #  Imprimimos esto para ver por consola
        print("+" * 90) #  Imprimimos esto para ver por consola
        return render(
            request,
            "cliente/cliente_formulario_basico.html",
        )
    else:
        print("*" * 90)     #  Imprimimos esto para ver por consola
        print(request.POST) #  Imprimimos esto para ver por consola
        print("*" * 90)     #  Imprimimos esto para ver por consola

        from .models import cliente 

        mi_cliente = cliente(nombre=request.POST["nombre"] , apellido=request.POST["apellido"], pais_origen = request.POST["pais_origen"], fecha_nacimiento= request.POST["fecha_nacimiento"])
        mi_cliente.save()
        return redirect("cliente:index")
        

def home(request):
    return render(request, "core/index.html")

project/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout 

def home(request):
    return render(request, "core/index.html")

def about(request):
    return render(request, "core/about.html")

def exit(request):
    logout(request)
    return redirect("core:index")

project/producto/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
    return render(request, "producto/index.html")

project/cliente/templates/cliente/cliente_formulario_basico.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>AppCoder</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
</head>
<body>

    {% include 'core/navbar.html' %}
    <!-- Page Content-->

    <div class="container px-4 px-lg-5">
        <h1>
            {% block contenido_titulo %}
                <h1>Registrar</h1>
            {% endblock contenido_titulo %}
        </h1>
 <!-- Register -->       

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario</title>
</head>

<body style="background-color: white;">
    <form action="/cliente/" method="POST">
        {% csrf_token %}
        <p>Nombre: <input type="text" name="nombre"> </p>
        <p>Apellido: <input type="text" name="Apellido"> </p>
        <p>Pais: <input type="text" name="pais_origen"> </p>
        <p>Fecha de Nacimiento: <input type="number" name="fecha_nacimiento"> </p>
        <input type="submit" value="Guardar">
    </form>
</body>

</html>

project/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
    Hola, soy la pestaña de CLIENTE!!!
    <h5>soy cliente</h5>
{% endblock contenido_titulo %}

{% block contenido %}
    <ul>
        <li><a href="{% url 'core:index' %}">Volver al inicio</a></li>
        <li><a href="{% url 'producto:index' %}">Ir a producto</a></li>
    </ul>
{% endblock contenido %}

project/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
    Nosotros
{% endblock contenido_titulo %}

{% block contenido %}
    <p>Hola! esto es un about :D </p>
{% endblock contenido %}<p>Hola! esto es un about :D </p>

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>AppCoder</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
        
    </head>
    <body>

        {% include 'core/navbar.html' %}
        <!-- Page Content-->

        <div class="container px-4 px-lg-5">
            <h1>
                {% block contenido_titulo %}
        
                {% endblock contenido_titulo %}
            </h1>

            {% block contenido %}
                
            {% endblock contenido %}
            <!-- Heading Row-->
          
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido_titulo %}
    {% if request.user.is_authenticated %}
    <h4>
        {{ user.username | upper }}, Bienvenido
    </h4>
    {% endif %}
    Comprá los mejores juegos
    <h5>Al mejor precio</h5>
{% endblock contenido_titulo %}

{% block contenido %}
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://d.newsweek.com/en/full/895239/god-war-4-trophy-guide-complete-list-all-how-get-gold-silver-bronze-platinum.jpg?w=1600&h=900&q=88&f=9f956e01f14bb50bd8c38f9793d10384" alt="..." /></div>
        <div class="col-lg-5">
            <h1 class="font-weight-light">¡Nuevo disponible nuestra tienda!</h1>
            <p>Con este juego de God of War vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer.</p>
            <a class="btn btn-primary" href="#!">¡Comprar ya!</a>
        </div>
    </div>
    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body"><p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p></div>
    </div>
{% endblock contenido %}

project/core/templates/core/navbar.html
<!--Navbar interactivo-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">GamerStore</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'producto:index' %}">Productos</a></li>
                
                {% if request.user.is_authenticated%}
                    <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}">Salir</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}">Ingresar</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">Nosotros</a></li>
            </ul>
        </div>
    </div>
</nav>

project/producto/templates/producto/index.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
    Productos destacados
    <h5>Los 3 únicos juegos que tenemos</h5>
{% endblock contenido_titulo %}

{% block contenido %}
    <ul>
        <li><a href="{% url 'core:index' %}">Volver al inicio</a></li>
        <li><a href="{% url 'cliente:index' %}">Ir a cliente</a></li>
    </ul>
    <div class="card" style="width: 18rem;">
        <img src="https://images.g2a.com/360x600/1x1x1/marvels-spider-man-remastered-pc-steam-key-global-i10000302546004/7e4252006f11418bae232b83" class="card-img-top" alt="...">
        <div class="card-body">
          <h2 class="card-title">Spider-Man Remastered</h2>
          <p class="card-text">$ 66.999</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
      </div>
      <div class="card" style="width: 18rem;">
        <img src="https://images.g2a.com/360x600/1x1x1/god-of-war-pc-steam-key-global-i10000152407005/98c4f59fc39f44aaa432445e" class="card-img-top" alt="...">
        <div class="card-body">
          <h2 class="card-title">God Of War</h2>
          <p class="card-text">$ 44.999</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
      </div>
      <div class="card" style="width: 18rem;">
        <img src="https://images.g2a.com/360x600/1x1x1/the-last-of-us-part-i-pc-steam-key-global-i10000326425006/ef73efe282954a74ab9bb70f" class="card-img-top" alt="...">
        <div class="card-body">
          <h2 class="card-title">The Last Of Us Part I</h2>
          <p class="card-text">$ 44.999</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
      </div>
{% endblock contenido %}